   window.ENV.SUPABASE_URL = "https://hgxtsgiabjkofimgbwek.supabase.co";
   window.ENV.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneHRzZ2lhYmprb2ZpbWdid2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg0MTA4NDQsImV4cCI6MjEwMzk4Njg0NH0.MDW8sDk04fzxko8ZN8piEWBYE7zxTDzExdjQNafTXxY";
